/* ================= Excel backups (download and Google Drive) ================= */
const DRIVE_FOLDER_DEFAULT="1A1aBRy2H9KE-Rp_HVLb2nZxeA6J_kmJl";
const driveFolder=()=>S.cfg.backupFolderId||DRIVE_FOLDER_DEFAULT;
const fmtX=v=>{ const t=ts(v); return isNaN(t)?"":dLocal(t).toISOString().slice(0,16).replace("T"," "); };
const flatStr=v=>v==null?"":Array.isArray(v)?v.map(x=>typeof x==="object"?JSON.stringify(x):x).join("; "):typeof v==="object"?JSON.stringify(v):String(v);
function caseRows(list){ return list.map(c=>{ const i=c.intake||{}, lm=c.lm||{}, r=c.review||{}, cl=c.closure||{}, st=stageTimes(c);
  return {"Reference":c.ref,"Venture":vInfo(c.venture).name,"Type":c.type,"Source":c.source,"Received":fmtX(c.receivedAt),"Registered":fmtX(c.createdAt),"Mobile":c.mobile,"Deal reference":c.dealRef,"LOB":c.lob,"Priority":c.priority,"Subject":c.subject,"Description":c.description,
   "Stage":ST[c.status],"Q&G owner":c.assigneeId?personName(c.assigneeId):"","Staff concerned":c.staffId?personName(c.staffId):"","Routed to team":i.teamId?teamName(i.teamId):"","Line manager":i.lmId?personName(i.lmId):"","Routed":fmtX(i.routedAt),
   "Q&G call attempts":(c.qgAttempts||[]).length,"LM call attempts":(lm.attempts||[]).length,"Resolution":lm.resolution||"","LM submitted":fmtX(lm.submittedAt),"Validity":r.verdict||"","Consequence":r.consequence||"","Consequence for":r.consequenceStaffId?personName(r.consequenceStaffId):"",
   "External closure":fmtX(cl.externalAt),"Internal closure":fmtX(cl.internalAt),"Q&G review hrs":st[2].end?Math.round(workHoursBetween(ts(st[2].start),ts(st[2].end),S.cfg)*10)/10:"","LM hrs":st[3].end?Math.round(workHoursBetween(ts(st[3].start),ts(st[3].end),S.cfg)*10)/10:"",
   "Business outcome":r.businessOutcome||"","Value at stake AED":r.businessValue??"","CSAT status":(c.csat||{}).status||"","CSAT score":(c.csat||{}).score??"","CSAT method":(c.csat||{}).method||"","Notes":(c.notes||[]).length,"Reminders sent":c.reminderCount||0,"Escalated":c.escalated?"Yes":"","Last updated":fmtX(c.updatedAt)}; }); }
function recRows(list){ return list.map(r=>{ const def=REG[r.section], o={"Reference":r.ref||r.id,"Section":(NAVMAP[r.section]||{label:r.section}).label,"Venture":vInfo(recVenture(r)).name};
  if(!def){ for(const [k,v] of Object.entries(r)) if(!["history","raw","imported","files"].includes(k)) o[k]=flatStr(v); return o; }
  for(const [k,l,t] of def.fields){ if(t==="ident"){ o["Mobile"]=r.mobile||""; o["Deal reference"]=r.dealRef||""; continue; } o[l]=t==="staff"?(r[k]?personName(r[k]):""):t==="lob"?String(r[k]||"").split("|")[1]||"":flatStr(r[k]); }
  Object.assign(o,{"Status":r.status,"Q&G owner":r.assigneeId?personName(r.assigneeId):"","Files":(r.files||[]).length,"Logged":fmtX(r.createdAt),"Logged by":r.createdByName||"","Last updated":fmtX(r.updatedAt),"Closed":fmtX(r.closedAt)}); return o; }); }
function evalRows(list){ return list.map(e=>{ const x=evalTimes(e); return {"Call ID":e.callId||e.id,"Venture":vInfo(e.ventureId||"insurancemarket").name,"LOB":e.lob,"Channel":e.channel,"Advisor":e.advisorName,"Score %":e.totalScore,"Fatal":e.hasFatalError?"Yes":"","Business outcome":e.businessOutcome||"","Status":e.status,"Interaction date":fmtX(e.interactionDate),"Started":fmtX(x.started),"Submitted":fmtX(x.submitted),"Handling min":x.handlingMin==null?"":Math.round(x.handlingMin),"Reviewed":fmtX(x.reviewed),"Review hrs":x.reviewHrs==null?"":Math.round(x.reviewHrs*10)/10,"Sent to advisor":fmtX(x.published),"Breaches":(e.policyBreaches||[]).length}; }); }
function buildWorkbook(ventureId){
  const XL=window.XLSX; if(!XL) throw new Error("The Excel library didn't load. Check your connection and reload.");
  const wb=XL.utils.book_new(), add=(name,rows)=>XL.utils.book_append_sheet(wb,XL.utils.json_to_sheet(rows.length?rows:[{"(empty)":""}]),name.slice(0,31));
  const vs=ventureId?[vInfo(ventureId)]:ventures();
  add("About",[{"Platform":"Q&G Platform · Alfred Holdings","Scope":ventureId?vInfo(ventureId).name:"All ventures, one set of sheets per venture","Generated (Dubai time)":fmtX(nowMs()),"Generated by":S.meName}]);
  for(const v of vs){
    const c=v.code||v.id.slice(0,3).toUpperCase();
    add(c+" Cases",caseRows(S.cases.filter(x=>x.venture===v.id)));
    add(c+" Records",recRows(S.recs.filter(r=>recVenture(r)===v.id)));
    add(c+" QA evaluations",evalRows(S.evals.filter(e=>(e.ventureId||"insurancemarket")===v.id)));
    add(c+" Recognition",S.rrEntries.filter(e=>e.venture===v.id).map(e=>{ const p=S.rrProgs.find(x=>x.id===e.programmeId)||{}; return {"Programme":p.name||"","Cycle":p.cycle||"","Group":rrGroup(p,e.groupId).name,"Person":personName(e.staffId),"Team":teamName(e.staffTeamId),"Sales":e.sales,"Claims managed":e.claimsManaged,"SLA %":e.slaPct,"Verified reviews":e.reviews,"Q&G score":RR_CRIT.reduce((s,[k])=>s+Number((e.scores||{})[k]||0),0)||"","Final result":e.finalResult||"","Disqualified":e.disqualified?e.disqualified.reason:"","Last updated":fmtX(e.updatedAt)}; }));
    add(c+" Time limit breaches",S.tatLog.filter(x=>x.venture===v.id).map(x=>({"Detected":fmtX(x.detectedAt),"Person":personName(x.staffId),"Manager":x.managerId?personName(x.managerId):"","Activity":x.activity,"Item":x.title,"Time":tatText(x),"Month":x.month})));
  }
  if(!ventureId){
    add("Staff",Object.values(S.staff).map(p=>({"Name":p.name,"Employee ID":p.employeeId,"Email":p.email,"Designation":p.designation,"Roles":(p.roles||[]).map(roleLabel).join(", "),"Team today":teamName((asgAt(p)||{}).teamId),"Team history":(p.assignments||[]).map(a=>teamName(a.teamId)+" "+a.from+" to "+(a.to||"present")).join("; "),"Last updated":fmtX(p.updatedAt)})));
    add("Teams",Object.values(S.teams).map(t=>({"Team":t.name,"Venture":vInfo(t.venture).name,"LOB":t.lob,"Kind":t.kind,"Line manager":personName(t.lineManagerId),"Superior":personName(t.superiorId),"Active":t.active===false?"No":"Yes"})));
    add("Tasks",S.tasks.map(t=>({"Task":t.title,"Venture":t.venture?vInfo(t.venture).name:"Group-wide","Assigned to":personName(t.assigneeId),"Status":t.status,"Due":t.due,"Created":fmtX(t.createdAt),"Done":fmtX(t.doneAt)})));
    add("Regulations",S.regs.map(r=>({"Title":r.title,"Authority":r.regulator,"Reference":r.refNo,"Status":r.status,"Effective":r.effective,"Applies to":(r.ventures||[]).join(", ")})));
    add("SOPs",S.sops.map(s=>({"Title":s.title,"Venture":s.venture||"all","Category":s.category,"Status":s.status,"Version":s.versions.length,"Last published":fmtX(s.versions[s.versions.length-1].at)})));
    add("Open questions",S.questions.map(q=>({"Section":(NAVMAP[q.section]||{label:"Platform-wide"}).label,"Question":q.q,"Status":q.status,"Answer":q.answer||"","Raised":fmtX(q.askedAt)})));
  }
  return wb;
}
async function downloadBackup(){
  if(!DOWNLOADS) return toast("Downloads aren't available in this view.");
  try{ const wb=buildWorkbook(S.venture); const b64=XLSX.write(wb,{bookType:"xlsx",type:"base64"});
    const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
    await DOWNLOADS.save({filename:`QG-Platform-${S.venture?vInfo(S.venture).code+"-":""}${todayD()}.xlsx`,data:new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})});
  }catch(e){ if(e&&e.code==="cancelled") return; toast(e.message||"The download didn't start."); }
}
async function driveBackup(auto){
  if(!MCP){ if(!auto) toast("Google Drive isn't connected in your session."); return false; }
  const day=todayD(), files=[];
  try{
    const sets=[["",`QG-Platform-backup-${day}-ALL.xlsx`],...ventures().map(v=>[v.id,`QG-Platform-backup-${day}-${v.code}.xlsx`])];
    for(const [v,title] of sets){
      const b64=XLSX.write(buildWorkbook(v),{bookType:"xlsx",type:"base64"});
      const res=await MCP.callTool("Google Drive","create_file",{title,base64Content:b64,contentMimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",disableConversionToGoogleType:true,parentId:driveFolder()});
      const p=(res&&res.payload)||{}; files.push({title,id:p.id||"",url:p.viewUrl||""});
    }
    await put("mod/sys/backups/"+day,{day,at:nowMs(),by:S.uid,byName:S.meName,auto:!!auto,files,status:"done"});
    if(!auto) toast(files.length+" backup files saved to Drive.");
    return true;
  }catch(e){
    await logError("backup",(auto?"Daily":"Manual")+" backup to Google Drive failed",{op:"driveBackup"},e);
    if(!auto) toast("The backup failed. It's in the error report.");
    return false;
  }
}
async function dailyBackupCheck(){
  if(!DB||!MCP||!S.admin||!window.XLSX) return;
  const day=todayD();
  if(S.backups.some(b=>b.day===day&&b.status==="done")) return;
  try{ const l=await DB.doc("mod/sys/locks/backup").acquire({holder:S.uid+"-"+SESSION,ttlMs:300000}); if(!l.acquired) return; }catch(_){ return; }
  await driveBackup(true);
}

/* ================= Bulk import (2026 data) ================= */
const IMPORT_TARGETS=()=>[["cases","Complaints and other cases"],["callbacks","Callback requests"],...Object.keys(REG).map(k=>[k,NAVMAP[k].label])];
function importCols(t){
  if(t==="cases"||t==="callbacks") return [["Received","date",1],["Type","text",t==="cases"],["Source","text",1],["Mobile","text",0],["Deal reference","text",0],["LOB","text",1],["Subject","text",1],["Description","text",1],["Priority","text",0],["Staff concerned","text",0],["Q&G owner","text",0],["Status","text",0],["Closed","date",0],["Validity","text",0],["Consequence","text",0],["Resolution","text",0],["Business outcome","text",0],["CSAT score","text",0]];
  return REG[t].fields.flatMap(([k,l,ty,req])=>ty==="ident"?[["Mobile","text",0],["Deal reference","text",0]]:[[l,ty==="date"?"date":"text",req]]).concat([["Status","text",0],["Q&G owner","text",0]]);
}
async function downloadTemplate(t){
  if(!DOWNLOADS||!window.XLSX) return toast("Downloads aren't available in this view.");
  const cols=importCols(t), XL=window.XLSX, wb=XL.utils.book_new();
  XL.utils.book_append_sheet(wb,XL.utils.aoa_to_sheet([cols.map(c=>c[0])]),"Data");
  const notes=[["Column","Required","Notes"],...cols.map(([l,ty,req])=>[l,req?"Yes":"",ty==="date"?"Date as YYYY-MM-DD or YYYY-MM-DD HH:MM (Dubai time)":l==="LOB"?"One of: "+((vInfo(S.ui.imp&&S.ui.imp.venture||S.venture).lobs)||[]).join(", "):/owner|concerned|Staff|Action owner|Raised to|Fix owner|Remediation owner/.test(l)?"Full name exactly as in Staff list":l==="Status"?(t==="cases"||t==="callbacks"?"Open or Closed":"One of: "+REG[t].statuses.join(", ")):""]),["","",""],["Customer details","","Only a mobile number or deal reference. Rows with email addresses are rejected."]];
  XL.utils.book_append_sheet(wb,XL.utils.aoa_to_sheet(notes),"How to fill");
  const b64=XL.write(wb,{bookType:"xlsx",type:"base64"});
  try{ await DOWNLOADS.save({filename:`QG-import-template-${t}.xlsx`,data:new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})}); }catch(e){ if(e&&e.code!=="cancelled") toast("The download didn't start."); }
}
function parseWhen(v){
  if(v==null||v==="") return NaN;
  if(typeof v==="number") return Math.round((v-25569)*864e5)-TZ; // Excel serial date, read as Dubai time
  const s=String(v).trim(), m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:[ T](\d{1,2}):(\d{2}))?/);
  if(m) return localToMs(`${m[1]}-${m[2]}-${m[3]}`,m[4]?m[4].padStart(2,"0")+":"+m[5]:"09:00");
  const d=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/); if(d) return localToMs(`${d[3]}-${d[2].padStart(2,"0")}-${d[1].padStart(2,"0")}`,"09:00");
  return NaN;
}
const byName=n=>{ const k=norm(n); return k?Object.values(S.staff).find(p=>norm(p.name)===k)||null:null; };
function validateImport(t,venture,rows){
  const v=vInfo(venture), lobsV=(v.lobs||[]).map(norm), out=[];
  rows.forEach((row,ix)=>{
    const g=k=>{ const key=Object.keys(row).find(x=>norm(x)===norm(k)); return key?row[key]:""; }, errs=[];
    for(const [l,ty,req] of importCols(t)){ const val=g(l); if(req&&(val===""||val==null)) errs.push(l+" is missing"); if(ty==="date"&&val!==""&&val!=null&&isNaN(parseWhen(val))) errs.push(l+" isn't a date"); }
    const lob=g("LOB")||g("Line of business"); if(lob&&!lobsV.includes(norm(lob))) errs.push(`LOB “${lob}” isn't a ${v.name} line of business`);
    const mob=g("Mobile"), deal=g("Deal reference");
    if((t==="cases"||t==="callbacks")&&!identOk(mob,deal)) errs.push("Needs a mobile number or deal reference");
    if(Object.values(row).some(x=>/@[^@\s]+\.[a-z]{2,}/i.test(String(x)))) errs.push("Contains an email address; remove customer details");
    const own=g("Q&G owner"); if(own&&!byName(own)) errs.push(`Q&G owner “${own}” isn't in Staff list`);
    out.push({ix:ix+2,row,g,errs,lob:(v.lobs||[]).find(x=>norm(x)===norm(lob))||""});
  });
  return out;
}
function viewImport(){
  const ui=S.ui.imp||(S.ui.imp={venture:S.venture||"",target:"cases",rows:null,res:null,busy:false});
  if(S.venture&&ui.venture!==S.venture) ui.venture=S.venture;
  const val=ui.rows&&ui.venture?validateImport(ui.target,ui.venture,ui.rows):null, ok=val?val.filter(x=>!x.errs.length):[], bad=val?val.filter(x=>x.errs.length):[];
  const last=[...S.backups].sort((a,b)=>b.at-a.at)[0];
  return `<section class="sect"><h2 class="h3">Daily backup</h2>
   <p class="lead">Each day, the first time you open the platform, it saves Excel backups to the “Q&G Platform backups” folder in Google Drive: one file per venture and one with everything. You can also run it or download a copy at any time.</p>
   <div class="stamps flat">${last?`Last backup ${stampCell(last.at)} by ${esc(last.byName||"")}${last.auto?" (automatic)":""} · ${(last.files||[]).length} files`:"No backup yet"}</div>
   <div class="row"><button class="btn primary" data-act="bkDrive">Back up to Drive now</button><button class="btn" data-act="bkDownload">Download Excel${S.venture?" for "+esc(vInfo(S.venture).name):" (all ventures)"}</button><a class="btn" href="https://drive.google.com/drive/folders/${esc(driveFolder())}" target="_blank" rel="noopener">Open the Drive folder</a></div>
   ${S.backups.length?`<div class="tbl" style="margin-top:12px"><table><thead><tr><th>Day</th><th>When</th><th>By</th><th>Type</th><th>Files</th></tr></thead><tbody>${[...S.backups].sort((a,b)=>b.at-a.at).slice(0,14).map(b=>`<tr><td>${esc(fmtD(b.day))}</td><td>${stampCell(b.at)}</td><td>${esc(b.byName||"")}</td><td>${b.auto?"Automatic":"Manual"}</td><td class="wrap">${(b.files||[]).map(f=>f.url?`<a href="${esc(f.url)}" target="_blank" rel="noopener">${esc(f.title)}</a>`:esc(f.title)).join("<br>")}</td></tr>`).join("")}</tbody></table></div>`:""}</section>
  <section class="sect"><h2 class="h3">Upload existing data</h2>
   <p class="lead">Every section also has its own “Upload existing data” button. You can start any upload from here too.</p>
   <div class="row"><select data-ui="impsel.t">${opts(impTargets().map(([v,l])=>({v,l})),(S.ui.impsel||{}).t||"complaints")}</select><button class="btn primary" data-act="impOpen" data-k="${esc((S.ui.impsel||{}).t||"complaints")}">Upload for this section</button></div>
   ${S.ui.imp3?impPanel(S.ui.imp3.target):""}
   <p class="hint">QA evaluations go in through the QA Evaluation tool's own Bulk upload, under Call evaluations.</p></section>
  ${viewImportHistory()}`;
}
async function importAction(act,el){
  const ui=S.ui.imp;
  if(act==="impTemplate") return downloadTemplate(ui.target);
  if(act==="impClear"){ ui.rows=null; ui.res=null; return; }
  if(act==="bkDrive"){ el.disabled=true; await driveBackup(false); return; }
  if(act==="bkDownload") return downloadBackup();
  if(act!=="impRun"||!S.admin) return;
  const val=validateImport(ui.target,ui.venture,ui.rows).filter(x=>!x.errs.length); if(!val.length) return;
  ui.busy=true; render(true);
  let done=0, failed=0; const t=ui.target, v=ui.venture, batchTag="IMP-"+todayD();
  for(const x of val){
    const g=x.g, own=byName(g("Q&G owner")), now=nowMs();
    try{
      if(t==="cases"||t==="callbacks"){
        const ref=await nextRef(t==="callbacks"?"CB":"CX"), rec=parseWhen(g("Received")), closed=/^closed$/i.test(String(g("Status")||"").trim()), cAt=parseWhen(g("Closed")), staff=byName(g("Staff concerned"));
        const c={ref,type:t==="callbacks"?"Callback request":(g("Type")||"Complaint"),source:g("Source"),receivedAt:rec,mobile:String(g("Mobile")||"").trim(),dealRef:String(g("Deal reference")||"").trim(),venture:v,lob:x.lob,subject:String(g("Subject")).trim(),description:String(g("Description")).trim(),priority:g("Priority")||"Normal",
          staffId:staff?staff.id:null,assigneeId:own?own.id:null,status:closed?"closed":"intake",stageAt:closed?(isNaN(cAt)?rec:cAt):now,createdAt:rec,updatedAt:now,createdBy:S.uid,createdByName:S.meName,imported:batchTag,intake:{},lm:{attempts:[],resolution:String(g("Resolution")||"")},
          review:closed?{verdict:g("Validity")||"",consequence:g("Consequence")||"None",finalSummary:String(g("Resolution")||""),businessOutcome:BIZ.find(b=>norm(b)===norm(g("Business outcome")))||"",at:isNaN(cAt)?rec:cAt,byName:"Imported"}:{},
          csat:closed&&Number(g("CSAT score"))>=1&&Number(g("CSAT score"))<=5?{status:"Captured",score:Math.round(Number(g("CSAT score"))),method:"Imported",at:isNaN(cAt)?rec:cAt,byName:"Imported"}:null,closure:closed?{externalAt:isNaN(cAt)?rec:cAt,internalAt:isNaN(cAt)?rec:cAt,externalByName:"Imported",internalByName:"Imported"}:{},
          timeline:[{at:now,by:S.uid,byName:S.meName,ev:"Imported",note:"From the 2026 data file, row "+x.ix}]};
        if(await put("mod/cx/cases/"+ref,c)) done++; else failed++;
      } else {
        const def=REG[t], out={};
        for(const [k,l,ty] of def.fields){ if(ty==="ident"){ out.mobile=String(g("Mobile")||"").trim(); out.dealRef=String(g("Deal reference")||"").trim(); continue; } const val=g(l);
          if(ty==="date") out[k]=isNaN(parseWhen(val))?"":dateOf(parseWhen(val)); else if(ty==="lob") out[k]=x.lob?v+"|"+x.lob:""; else if(ty==="staff"){ const p=byName(val); out[k]=p?p.id:null; if(p) out[k+"Team"]=(asgAt(p,out.date)||{}).teamId||null; } else out[k]=val==null?"":String(val).trim(); }
        const st=def.statuses.find(s=>norm(s)===norm(g("Status")))||def.statuses[0], ref=await nextRef(def.prefix), created=parseWhen(g(def.fields[0][1]));
        const doc={id:ref,ref,section:t,...out,venture:v,status:st,assigneeId:own?own.id:null,createdAt:isNaN(created)?now:created,updatedAt:now,closedAt:def.final.includes(st)?now:null,createdBy:S.uid,createdByName:S.meName,imported:batchTag,history:[{at:now,byName:S.meName,note:"Imported from the 2026 data file, row "+x.ix}]};
        if(await put("mod/reg/records/"+ref,doc)) done++; else failed++;
      }
    }catch(e){ failed++; }
    if((done+failed)%10===0){ ui.res=`Imported ${done} of ${val.length}…`; render(true); }
  }
  await addAudit("import",batchTag,"Imported "+done+" rows",null,null,`${vInfo(v).name} · ${t} · ${done} imported, ${failed} failed`);
  ui.busy=false; ui.rows=null; ui.res=`Imported ${done} row${done===1?"":"s"} into ${vInfo(v).name}${failed?`; ${failed} failed and are in the error report`:""}.`;
}
async function readImportFile(file){
  const ui=S.ui.imp; if(!window.XLSX) return toast("The Excel library didn't load. Reload and try again.");
  try{ const buf=await file.arrayBuffer(), wb=XLSX.read(buf,{type:"array",cellDates:false}), sh=wb.Sheets[wb.SheetNames[0]];
    ui.rows=XLSX.utils.sheet_to_json(sh,{defval:"",raw:true}).filter(r=>Object.values(r).some(x=>String(x).trim()!==""));
    ui.res=null; if(ui.rows.length>5000){ ui.rows=ui.rows.slice(0,5000); ui.res="Only the first 5,000 rows are read per file. Split larger files."; }
  }catch(e){ toast("That file couldn't be read. Use the template, saved as .xlsx or .csv."); }
}
